{{- if .Values.tls_certificates_from_secret.generate_certificate -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls_certificates_from_secret.certificate.commonName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "389server.labels" . | nindent 4 }}
spec:
  commonName: {{ .Values.tls_certificates_from_secret.certificate.commonName }}
  dnsNames:
  {{- .Values.tls_certificates_from_secret.certificate.dnsNames | toYaml | nindent 4 }}
  issuerRef:
    name:  {{ .Values.tls_certificates_from_secret.certificate.issuerRef.name }}
    kind:  {{ .Values.tls_certificates_from_secret.certificate.issuerRef.kind }}
  secretName:  {{ .Values.tls_certificates_from_secret.certificate.secretName }}
{{- end -}}
